# --- !Ups

CREATE TABLE Users (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL UNIQUE,
  Password BLOB NOT NULL,
  Salt BLOB NOT NULL,
  ApiKey VARCHAR(70) NOT NULL UNIQUE,
  CreatedOn TIMESTAMP NOT NULL,
  FailedAttempts INTEGER NOT NULL DEFAULT 0,
  Blocked BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (Id)
);

CREATE TABLE Groups (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL UNIQUE,
  Description VARCHAR(255) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE Permissions (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL UNIQUE,
  Description VARCHAR(255) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE Apps (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL UNIQUE,
  Description VARCHAR(255) NOT NULL,
  PRIMARY KEY (Id)
);

# --- !Downs

DROP TABLE Users;
DROP TABLE Groups;
DROP TABLE Permissions;
DROP TABLE Apps;
