# --- !Ups

CREATE TABLE Users (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Password BLOB NOT NULL,
  Salt BLOB NOT NULL,
  ApiKey VARCHAR(70) NOT NULL,
  CreatedOn TIMESTAMP NOT NULL,
  FailedAttempts INTEGER NOT NULL DEFAULT 0,
  Blocked BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (Id),
  UNIQUE ( Email ),
  UNIQUE ( ApiKey )
);

CREATE TABLE Groups (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Description VARCHAR(255) NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE ( Name )
);

CREATE TABLE Permissions (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(50) NOT NULL,
  Description VARCHAR(255) NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE ( Name )
);

CREATE TABLE UsersGroups (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  UserId BIGINT NOT NULL REFERENCES Users (Id),
  GroupId BIGINT NOT NULL REFERENCES Groups (Id),
  PRIMARY KEY (Id),
  UNIQUE (UserId, GroupId)
);

CREATE TABLE GroupsPermissions (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  GroupId BIGINT NOT NULL REFERENCES Groups (Id),
  PermissionId BIGINT NOT NULL REFERENCES Permissions (Id),
  PRIMARY KEY (Id),
  UNIQUE (GroupId, PermissionId)
);

# --- !Downs

DROP TABLE Users;
DROP TABLE Groups;
DROP TABLE Permissions;

DROP TABLE UsersGroups;
DROP TABLE GroupsPermissions;
